- name: 📌 Stars + Languages
  uses: lowlighter/metrics@v3
  with:
    filename: metrics.svg
    token: ${{ secrets.TOKEN }}
    base: ""
    output_action: local

    plugin_stars: yes
    plugin_stars_limit: 5

    plugin_languages: yes
    plugin_languages_sections: recently-used
    plugin_languages_limit: 5
    plugin_languages_details: percentage