name: Metrics

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.TOKEN }}
          base: header
          output_action: commit

          plugin_stars: yes
          plugin_stars_limit: 5

          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_limit: 5
          plugin_languages_details: percentage